[package]
name = "gtrace"
version = "0.1.0"
authors = ["Geoffrey Thomas <geofft@ldpreload.com>"]

[dependencies]
nix = { git = "https://github.com/nix-rust/nix" }
libc = "0.2"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
gtrace-derive = { path = "gtrace-derive" }
